/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppApplicantDetails {
    }
    interface AppApplicationSection {
    }
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface AppSchoolDashboard {
    }
    interface AppSchoolRegister {
    }
    interface AppStudentRegister {
    }
}
declare global {
    interface HTMLAppApplicantDetailsElement extends Components.AppApplicantDetails, HTMLStencilElement {
    }
    var HTMLAppApplicantDetailsElement: {
        prototype: HTMLAppApplicantDetailsElement;
        new (): HTMLAppApplicantDetailsElement;
    };
    interface HTMLAppApplicationSectionElement extends Components.AppApplicationSection, HTMLStencilElement {
    }
    var HTMLAppApplicationSectionElement: {
        prototype: HTMLAppApplicationSectionElement;
        new (): HTMLAppApplicationSectionElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSchoolDashboardElement extends Components.AppSchoolDashboard, HTMLStencilElement {
    }
    var HTMLAppSchoolDashboardElement: {
        prototype: HTMLAppSchoolDashboardElement;
        new (): HTMLAppSchoolDashboardElement;
    };
    interface HTMLAppSchoolRegisterElement extends Components.AppSchoolRegister, HTMLStencilElement {
    }
    var HTMLAppSchoolRegisterElement: {
        prototype: HTMLAppSchoolRegisterElement;
        new (): HTMLAppSchoolRegisterElement;
    };
    interface HTMLAppStudentRegisterElement extends Components.AppStudentRegister, HTMLStencilElement {
    }
    var HTMLAppStudentRegisterElement: {
        prototype: HTMLAppStudentRegisterElement;
        new (): HTMLAppStudentRegisterElement;
    };
    interface HTMLElementTagNameMap {
        "app-applicant-details": HTMLAppApplicantDetailsElement;
        "app-application-section": HTMLAppApplicationSectionElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-school-dashboard": HTMLAppSchoolDashboardElement;
        "app-school-register": HTMLAppSchoolRegisterElement;
        "app-student-register": HTMLAppStudentRegisterElement;
    }
}
declare namespace LocalJSX {
    interface AppApplicantDetails {
    }
    interface AppApplicationSection {
    }
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface AppSchoolDashboard {
    }
    interface AppSchoolRegister {
    }
    interface AppStudentRegister {
    }
    interface IntrinsicElements {
        "app-applicant-details": AppApplicantDetails;
        "app-application-section": AppApplicationSection;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-school-dashboard": AppSchoolDashboard;
        "app-school-register": AppSchoolRegister;
        "app-student-register": AppStudentRegister;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-applicant-details": LocalJSX.AppApplicantDetails & JSXBase.HTMLAttributes<HTMLAppApplicantDetailsElement>;
            "app-application-section": LocalJSX.AppApplicationSection & JSXBase.HTMLAttributes<HTMLAppApplicationSectionElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-school-dashboard": LocalJSX.AppSchoolDashboard & JSXBase.HTMLAttributes<HTMLAppSchoolDashboardElement>;
            "app-school-register": LocalJSX.AppSchoolRegister & JSXBase.HTMLAttributes<HTMLAppSchoolRegisterElement>;
            "app-student-register": LocalJSX.AppStudentRegister & JSXBase.HTMLAttributes<HTMLAppStudentRegisterElement>;
        }
    }
}
